set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
set-option -g focus-events on
set-option -sg escape-time 10
bind r source-file ~/.tmux.conf \; display "Reload!"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind - split-window -v
bind | split-window -h
